# Generated by Django 4.2 on 2023-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('Type', models.CharField(choices=[('suregon', 'suregon'), ('general', 'general')], max_length=50)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
